// quick-lint-js finds bugs in JavaScript programs.
// Copyright (C) 2020  Matthew Glazar
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#ifndef QUICK_LINT_JS_GMO_H
#define QUICK_LINT_JS_GMO_H

#include <cstdint>
#include <string_view>

namespace quick_lint_js {
// gmo_file gives access to data within a GNU MO file.
//
// A GNU MO file stores translations. It is generated by GNU gettext's msgfmt
// command.
//
// TODO(strager): Make this parser robust. gmo_file currently trusts the input
// and assumes it is valid.
class gmo_file {
 public:
  using offset_type = std::uint32_t;
  using word_type = std::uint32_t;

  explicit gmo_file(const void *data) noexcept;

  word_type string_count() const noexcept;

  std::string_view original_string_at(word_type index) const noexcept;
  std::string_view translated_string_at(word_type index) const noexcept;

  std::string_view find_translation(std::string_view original) const noexcept;

  static word_type hash_string(std::string_view) noexcept;

 private:
  std::string_view find_translation_scanning(std::string_view original) const
      noexcept;
  std::string_view find_translation_hashing(std::string_view original) const
      noexcept;

  word_type read_word(word_type offset) const noexcept;
  word_type read_word_little_endian(word_type offset) const noexcept;
  word_type read_word_big_endian(word_type offset) const noexcept;

  word_type hash_table_size() const noexcept;
  offset_type original_strings_offset() const noexcept;
  offset_type translated_strings_offset() const noexcept;

  std::string_view string_at(offset_type table_offset, word_type index) const
      noexcept;

  bool is_little_endian() const noexcept;

  const std::uint8_t *data_;
};
}

#endif
