// quick-lint-js finds bugs in JavaScript programs.
// Copyright (C) 2020  Matthew Glazar
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#ifndef QUICK_LINT_JS_TRANSLATION_DATA_H
#define QUICK_LINT_JS_TRANSLATION_DATA_H

#include <quick-lint-js/locale.h>

namespace quick_lint_js {
// List of compiled translation files (.mo files) generated by GNU gettext's
// msgfmt command.
//
// These .mo files are embedded into the executable to simplify deployment.
extern const locale_entry<const std::uint8_t*> gmo_files[];
}

#endif
