#!/bin/sh

# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

set -e
set -u

cd "$(dirname "${0}")"

zip_path="$(pwd)/quick-lint-js-vim.zip"

rm -f "${zip_path}"
zip -9 -r "${zip_path}" \
  quick-lint-js.vim/ \
  README.md
cd ../..
zip -9 "${zip_path}" COPYING

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
