#!/usr/bin/env bash

# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

set -e
set -o pipefail
set -u

cd "$(dirname "${0}")/.."
source tools/files.sh

parallelism=$(nproc 2>/dev/null)
if [[ -z "${parallelism}" ]]; then
  parallelism=3
fi

files_to_parse=($(find_non_vendor_files | matching '\.(c|cpp|h)$'))
chunk_size=$(((${#files_to_parse[@]} + ${parallelism} - 1) / ${parallelism}))

printf '%s\n' "${files_to_parse[@]}" \
  | xargs "-P${parallelism}" "-n${chunk_size}" clang-format -i

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
