#!/usr/bin/env bash

# Copyright (C) 2020  Matthew "strager" Glazar
# See end of file for extended copyright information.

set -e
set -u

cd "$(dirname "${0}")/.."

main() {
  check_dependencies

  local po_flags=()
  for po_file in po/*.po; do
    po_flags+=(--po "${po_file}")
  done
  ./build/quick-lint-js-compile-translations \
    --source benchmark/benchmark-translation.cpp \
    --source src/quick-lint-js/diag/diagnostic-formatter.cpp \
    --source src/quick-lint-js/diag/diagnostic-metadata-generated.cpp \
    --source src/quick-lint-js/diag/diagnostic-metadata-generated.h \
    --source test/test-diagnostic-formatter.cpp \
    --source test/test-vim-qflist-json-diag-reporter.cpp \
    --output-messages-pot po/messages.pot \
    --output-translation-table-h src/quick-lint-js/i18n/translation-table-generated.h \
    --output-translation-table-cpp src/quick-lint-js/i18n/translation-table-generated.cpp \
    --output-translation-table-test test/quick-lint-js/test-translation-table-generated.h \
    "${po_flags[@]}"

  update_translation_files
}

check_dependencies() {
  xgettext_version="$(xgettext -V 2>/dev/null)" || printf 'warning: xgettext is required\n'

  if ! [ -x ./build/quick-lint-js-compile-translations ]; then
      printf "error: missing build/quick-lint-js-compile-translations (compile it with 'ninja -C build quick-lint-js-compile-translations')\n" 2>&1
      exit 1
  fi
}

update_translation_files() {
  for po_file in po/*.po ; do
    printf 'updating: %s\n' "${po_file}"
    msgmerge --backup=none --update -- "${po_file}" po/messages.pot
  done
}

main

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew "strager" Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
