#!/bin/sh

# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

set -e
set -u

output_directory="${1}"
mkdir -p "${output_directory}"
output_directory="$(cd "${output_directory}" && pwd)"

cd "$(dirname "${0}")"

cp atom.svg "${output_directory}/"
cp cli.md "${output_directory}/"
cp debian.svg "${output_directory}/"
cp emacs.svg "${output_directory}/"
cp gnome-terminal.svg "${output_directory}/"
cp hiring.md "${output_directory}/"
cp homebrew.svg "${output_directory}/"
cp index.html "${output_directory}/"
cp license.md "${output_directory}/"
cp linux.svg "${output_directory}/"
cp macos.svg "${output_directory}/"
cp main.css "${output_directory}/"
cp nix.svg "${output_directory}/"
cp notepad-plus-plus.svg "${output_directory}/"
cp npm.svg "${output_directory}/"
cp sublime-text.svg "${output_directory}/"
cp ubuntu.svg "${output_directory}/"
cp vim.gif "${output_directory}/"
cp vscode-demo.mp4 "${output_directory}/"
cp vscode-demo.png "${output_directory}/"
cp vscode-demo.webp "${output_directory}/"
cp vscode.png "${output_directory}/"
cp webstorm.svg "${output_directory}/"
cp windows.svg "${output_directory}/"

mkdir -p "${output_directory}/demo/"
cp demo/carat.svg "${output_directory}/demo/"
cp demo/editor.mjs "${output_directory}/demo/"
cp demo/index.html "${output_directory}/demo/"
cp demo/quick-lint-js.mjs "${output_directory}/demo/"

mkdir -p "${output_directory}/demo/dist/"
cp demo/dist/copyright.txt "${output_directory}/demo/dist/"
cp demo/dist/quick-lint-js-wasm-demo.js "${output_directory}/demo/dist/"
cp demo/dist/quick-lint-js-wasm-demo.wasm "${output_directory}/demo/dist/"

mkdir -p "${output_directory}/cli/"
cp cli/index.html "${output_directory}/cli"

mkdir -p "${output_directory}/benchmarks/"
cp benchmarks/benchmark.css "${output_directory}/benchmarks/"
cp benchmarks/benchmark.mjs "${output_directory}/benchmarks/"
cp benchmarks/index.html "${output_directory}/benchmarks/"

mkdir -p "${output_directory}/errors/"
cp errors/index.html "${output_directory}/errors/"

mkdir -p "${output_directory}/hiring/"
cp hiring/index.html "${output_directory}/hiring/"

mkdir -p "${output_directory}/install/"
cp install/index.html "${output_directory}/install/"

mkdir -p "${output_directory}/license/"
cp license/index.html "${output_directory}/license/"

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
