# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

name: build website
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: website
    runs-on: ubuntu-latest
    container: ghcr.io/quick-lint/quick-lint-js-github-builder:v3
    env:
      QLJS_COLLECT_COPYRIGHT_NO_WARNINGS: 1
    steps:
      - uses: mymindstorm/setup-emsdk@v7
        with:
          version: 2.0.4
      - name: checkout
        uses: actions/checkout@v2

      - name: C++ configure
        run: emcmake cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS='-Os -flto' -DCMAKE_CXX_FLAGS='-Os -fno-rtti -fno-exceptions -flto'
      - name: C++ build
        run: emmake cmake --build build --target quick-lint-js-vscode quick-lint-js-vscode-licenses
      - name: C++ install
        run: |
          emmake cmake --install build --component vscode --prefix wasm
          emmake cmake --install build --component vscode --prefix website/public/demo

      - name: JS configure
        run: cd website && yarn
      - name: JS test
        run: cd website && yarn test

      - name: build site
        run: cd website && yarn build
      - name: bundle site
        run: cd website && zip -r ../website.zip www

      - name: set up check-links
        run: |
          python3.7 -m venv ENV
          ENV/bin/pip install bs4 requests
      - name: check links (dev)
        run: |
          cd website/
          yarn start localhost 9001 &
          sleep 0.5  # HACK(strager): Wait for server to start.
          cd ../
          ./ENV/bin/python ./tools/check-links http://localhost:9001/
          kill %1
        shell: bash
      - name: check links (build)
        run: |
          cd website/www/
          python3.7 -m http.server 9002 &
          sleep 0.5  # HACK(strager): Wait for server to start.
          cd ../../
          ./ENV/bin/python ./tools/check-links http://localhost:9002/
          kill %1
        shell: bash

      - name: upload build to workflow
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: website-${{ github.sha }}
          path: website/www/
      - name: upload build to long-term storage
        if: ${{ github.event_name == 'push' && github.repository_owner == 'quick-lint' != null }}
        uses: quick-lint/sftp-upload@master
        with:
          host: ${{ secrets.artifacts_host }}
          local-file-globs: website.zip
          private-key: ${{ secrets.artifacts_key }}
          remote-directory: ${{ secrets.artifacts_root }}/builds/${{ github.sha }}/website/
          user: ${{ secrets.artifacts_user }}

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
