# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

name: CLA
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize]

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant
        if: |
          github.event_name == 'pull_request_target' || github.event.comment.body == 'I have read and hereby agree to quick-lint-js'' Contributor License Agreement (CLA-v1.md).' || github.event.comment.body == 'recheck'
        uses: cla-assistant/github-action@v2.1.2-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_ASSISTANT_PERSONAL_ACCESS_TOKEN }}
        with:
          lock-pullrequest-aftermerge: false
          path-to-document: https://github.com/quick-lint/quick-lint-js/blob/master/docs/CLA-v1.md

          # Commit the signatures to a separate repository.
          branch: master
          path-to-signatures: CLA-v1.json
          remote-organization-name: quick-lint
          remote-repository-name: quick-lint-js-cla

          create-file-commit-message: Update CLA signatures
          custom-allsigned-prcomment: "All contributors have signed quick-lint-js' Contributor License Agreement (CLA-v1.md)."
          custom-notsigned-prcomment: "Thank you for your contribution! Like many free software projects, you must sign our [Contributor License Agreement](https://github.com/quick-lint/quick-lint-js/blob/master/docs/CLA-v1.md) before we can accept your contribution. You can agree to the Contributor License Agreement by copy-pasting the following message into a new comment on this GitHub pull request:"
          custom-pr-sign-comment: "I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md)."
          signed-commit-message: 'Add CLAv1 signature: $contributorName signed in PR #$pullRequestNo'

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
